### ISSUE TITLE
Fix spacing of lines with notes

### ISSUE THREAD

**Issue by jboynyc** [Carpetsmoker/hello-css#5]
Right now spacing is uneven in lines that contain footnotes.

Including this should fix the issue:

```css
/* Make sure footnotes don't mess up line spacing */
sup,sub {
    height: 0;
    line-height: 1;
    vertical-align: baseline;
    position: relative;
}
sup {
    bottom: 1ex;
}
sub {
    top: .5ex;
}
```
